### PR TITLE
Rdma Engine Fix-Ups

### PR DESCRIPTION
**Pull request by lsgunth**
Hi,

Here are a couple patches that improves the RDMA engine flow.  Please see the individual commits for a description of each problem.

Thanks,

Logan

### CODE REVIEW

**Comment by axboe** [comment]
Looks OK to me, pulled. Thanks!

**Comment by sbates130272** [comment]
Hi

Did this get pulled? I don't see it in the master branch of GitHub fio? Is the mirroring working?

Thanks

Stephen

**Comment by axboe** [comment]
It did, but apparently I forgot to push it on Friday. Pushed now to the master repo (git.kernel.dk), it'll bubble out to git.kernel.org and github.com within the hour.

**Comment by sbates130272** [comment]
Great, thanks!

**Pull request closed without merging**
