### PR TITLE
fio2gnuplot: fix TabErrors when running with Python 3

### LINKED ISSUE #804: Multiple TabError's when trying to run fio2gnuplot with Python 3
`tools/plot/fio2gnuplot` cannot be run with Python 3 because it mixes tabs with spaces which became SyntaxError in Python 3.
```
❯ python fio2gnuplot    
  File "fio2gnuplot", line 42
    fio_data_file.append(file)
                             ^
TabError: inconsistent use of tabs and spaces in indentation
```
There are more of them.

### PR DESCRIPTION
**Pull request by kapsh**
Closes #804

Signed-off-by: Alexander Kapshuna <kapsh@kap.sh>

### CODE REVIEW

**Comment by sitsofe** [comment]
LGTM!

**Comment by sitsofe** [comment]
@axboe This one looks fine to me :-)

**Comment by axboe** [comment]
Pulled, thanks.

**Comment by kapsh** [comment]
Appreciate it.

**Pull request merged**
