### PR TITLE
windowsaio: add best effort invalidation

### PR DESCRIPTION
**Pull request by sitsofe**
https://stackoverflow.com/questions/478340/clear-file-cache-to-repeat-perf`ormance-testing/7113153#7113153
mentions that opening a file without buffering on Windows has the side
effect of flushing cached parts of the file out of RAM. Use this side
effect to do cache invalidation on non-direct jobs that are using the
windowsaio engine. Note this invalidation will fail if the file is also
open elsewhere and we can't check whether we have exclusive access
without introducing a race where other jobs fail while we temporarily
have exclusive access to the file.

Preliminary pull request to gather suggestions and feedback.

### CODE REVIEW

**Comment by sitsofe** [comment]
@bcran any thoughts on this one?

**Comment by axboe** [comment]
Looks useful! I'd probably put the invalidation code into a separate function instead of inlining it, however.

**Comment by sitsofe** [comment]
OK update with invalidation has been moved to its own function and the commit message has been made longer.

**Comment by sitsofe** [comment]
@axboe just a quick ping on this one.

**Comment by axboe** [comment]
Pulled, thanks. Just a minor note not to use braces for single line if blocks, fio generally doesn't do that.

**Comment by sitsofe** [comment]
Oops, sorry about that one.

**Pull request merged**
