### PR TITLE
io_uring: only use rand48_r functions for glibc

### PR DESCRIPTION
**Pull request by neheb**
These break compilation under musl. They are also glibc specific.

### CODE REVIEW

**Comment by axboe** [comment]
This silently breaks seeding, for repeated runs or for verification purposes.

**Comment by neheb** [comment]
That's unfortunate.

**Comment by axboe** [comment]
Ah I'm blind, it's just t/io_uring. I'll fix this up a bit differently, we should just use the local helpers.

**Comment by axboe** [comment]
Killed it, closing this one.

**Pull request closed without merging**
