### PR TITLE
Add /t/fuzz/fuzz_parseini to .gitignore

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/axboe/fio/1190)

### CODE REVIEW

**Review by sitsofe — CHANGES_REQUESTED** [review]
@ldorau Usual fio commit message title style is `area: brief summary`. Maybe `.gitignore: add /t/fuzz/fuzz_parseini`?

**Review by ldorau — COMMENTED** [review]
OK. Done.

> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1190#-:-MY3UzTC66q3LrAzNiyy:b-k1y5pj)* status: 0 of 1 files reviewed, all discussions resolved

**Review by sitsofe — APPROVED** [review]
LGTM!

@axboe can this be pulled?

**Comment by axboe** [comment]
That particular change had already been merged.

**Pull request merged**
