### PR TITLE
Add GitHub Actions / retire Travis

### PR DESCRIPTION
**Pull request by sitsofe**
- Add GitHub actions CI
- Retire Travis CI :-(. See https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing for how abuse forced Travis to change its billing model

### CODE REVIEW

**Comment by ldorau** [comment]
The 'linux-i686-gcc' build always fails on my fork:
https://github.com/ldorau/fio/actions/runs/517647494
@sitsofe Do you know why?

**Comment by ldorau** [comment]
> @sitsofe Do you know why?

I meant: why does it fail on my GH fork, but it succeeds on yours (having the same code on both forks) ?

**Comment by ldorau** [comment]
The error is following:
```
Setting up pkg-config:i386 (0.29.1-0ubuntu4) ...
E: Could not configure 'libc6:i386'. 
E: Could not perform immediate configuration on 'libgcc-s1:i386'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
Error: Process completed with exit code 100.
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1157)* status: 2 of 9 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1157)* status: 4 of 9 files reviewed, all discussions resolved

**Comment by sitsofe** [comment]
@ldorau That looks like https://bugs.launchpad.net/ubuntu-cdimage/+bug/1871268 (see from comment `#188` onwards), no?

**Review by ldorau — COMMENTED** [review]
@sitsofe Yes, that's right. Thanks!
That fixes the linux i686 build:
https://github.com/pmem/fio/pull/199

> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1157#-:-MSROLgWE8Jlv3cfDwvi:b-o3lgry)* status: 4 of 9 files reviewed, all discussions resolved

**Comment by sitsofe** [comment]
(@ldorau BTW I stumbled across that launchpad issue with a [Google search for "Could not perform immediate configuration on 'libgcc-s1:i386'."](https://www.google.com/search?q=Could+not+perform+immediate+configuration+on+%27libgcc-s1%3Ai386%27.))

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1157)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @sitsofe)

___
*[.github/workflows/ci.yml, line 26 at r1](https://reviewable.io/reviews/axboe/fio/1157#-MSRW1QoABTooW_4qlrS:-MSRW1QoABTooW_4qlrT:b-j6exf2) ([raw file](https://github.com/axboe/fio/blob/9eaf8b756882a56b8e730987e04b34c9970c6b22/.github/workflows/ci.yml#L26)):*
> ```
>  macos-11.0
> ```

The macOS 11.0 ('macos-11.0') virtual environment is currently provided as a private preview only:

https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners

`macos-latest` should be used instead.

**Review by ldorau — COMMENTED** [review]
> Reviewed 5 of 9 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sitsofe)

**Comment by sitsofe** [comment]
@ldorau Thanks! I've updated this PR.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sitsofe)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sitsofe)

*[a discussion](https://reviewable.io/reviews/axboe/fio/1157#-MSRkp4B21lBT0ZOKwCv:-MSRkp4B21lBT0ZOKwCw:b-8p1yh2) (no related file):*
@sitsofe I have to apply also the following fix to make the macos build work on my fork:
https://github.com/pmem/fio/pull/200/commits/c82faa4f90c567ceeac4858826bb14318ab3f2c4 (on https://github.com/pmem/fio/pull/200)

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1157)* status: all files reviewed, 2 unresolved discussions (waiting on @sitsofe)

___
*[ci/actions-install.sh, line 38 at r4](https://reviewable.io/reviews/axboe/fio/1157#-MSRmSD69HGExNTgaiFh:-MSRmSD69HGExNTgaiFi:b-p5zzeo) ([raw file](https://github.com/axboe/fio/blob/6ce13de4e5c4977ead3aa3da23c57401a069892d/ci/actions-install.sh#L38)):*
> ```
>                 pkg-config:i386
>                 pkg-config:i386
> ```

Doubled
___
*[ci/actions-install.sh, line 39 at r4](https://reviewable.io/reviews/axboe/fio/1157#-MSRm9Mr8mMpNJk0yvit:-MSRm9Mr8mMpNJk0yviu:b-6072ln) ([raw file](https://github.com/axboe/fio/blob/6ce13de4e5c4977ead3aa3da23c57401a069892d/ci/actions-install.sh#L39)):*
> ```
> zlib1g-dev:i386
> ```

You have used tabs instead of spaces in this one line.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sitsofe)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sitsofe)

*[a discussion](https://reviewable.io/reviews/axboe/fio/1157#-MSRkp4B21lBT0ZOKwCv:-MSWxh-L2ZttreE1UpR3:b-gxxnw6) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@sitsofe I have to apply also the following fix to make the macos build work on my fork:
https://github.com/pmem/fio/pull/200/commits/c82faa4f90c567ceeac4858826bb14318ab3f2c4 (on https://github.com/pmem/fio/pull/200)
</blockquote></details>

After having installed `zlib1g-dev:i386` it is not needed :-)

---

**Review by ldorau — COMMENTED** [review]
The GHA build passes on my fork now: https://github.com/ldorau/fio/actions/runs/530211284

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1157#-:-MSWxx4C12Ie5j7UxU45:b1zv14m)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sitsofe)

**Comment by sitsofe** [comment]
@axboe Travis stopped working earlier in the year... What do you think of this one?

**Comment by axboe** [comment]
Let's go for it, we've got nothing to lose :-)

**Pull request merged**
