### PR TITLE
server: only do cpu_to_le64() on io_sample_data member if iolog is histogram

### PR DESCRIPTION
**Pull request by tuan-hoang1**
Signed-off-by: Ulrich Weigand <ulrich.weigand@de.ibm.com>
Signed-off-by: Tuan Hoang <tuan.hoang1@ibm.com>

### CODE REVIEW

**Comment by tuan-hoang1** [comment]
Hi @axboe, I also think there is also a similar check in client.c as well (see below). What do you think ? 
```
diff --git a/client.c b/client.c
index 605a3ce5..37da74bc 100644
--- a/client.c
+++ b/client.c
@@ -1702,7 +1702,8 @@ static struct cmd_iolog_pdu *convert_iolog(struct fio_net_cmd *cmd,
                        s = (struct io_sample *)((char *)s + sizeof(struct io_u_plat_entry) * i);
 
                s->time         = le64_to_cpu(s->time);
-               s->data.val     = le64_to_cpu(s->data.val);
+               if (ret->log_type != IO_LOG_TYPE_HIST)
+                       s->data.val     = le64_to_cpu(s->data.val);
                s->__ddir       = __le32_to_cpu(s->__ddir);
                s->bs           = le64_to_cpu(s->bs);
                s->priority     = le16_to_cpu(s->priority);

```

**Comment by axboe** [comment]
Can you put an actual commit message in there? A good commit message should explain WHY the change is being made, but there's nothing in there I can't just learn from looking at the change itself.

**Comment by tuan-hoang1** [comment]
> Can you put an actual commit message in there? A good commit message should explain WHY the change is being made, but there's nothing in there I can't just learn from looking at the change itself.

I just updated. Thanks !

**Comment by axboe** [comment]
Great, thanks! That makes sense. Agree on the client side fwiw - if we need this on the server side, client side should do the same. I'm going to merge this one, please send one for the client code as well. Thanks.

**Pull request merged**
