### PR TITLE
fio: add libiscsi engine

### PR DESCRIPTION
**Pull request by kylezh**
Adding a new engine that access iscsi lun with libiscsi.

Signed-off-by: Kyle Zhang <kyle@smartx.com>

### CODE REVIEW

**Comment by sitsofe** [comment]
You beat me to the punch :-) Any chance you can look at https://github.com/sitsofe/fio/tree/libiscsi and see if there's anything there you can take/steal?

**Comment by kylezh** [comment]
@sitsofe haha~
I haven't know that there is already an implementation of fio iscsi engine. So I just wrote a quite simple one by myself.
Why not make a PR from https://github.com/sitsofe/fio/tree/libiscsi ? Seems that your branch has more features than mine.

**Comment by axboe** [comment]
This looks pretty clean, good job. Any chance you can include a sample job file as well? That's usually pretty helpful for new users. Would also be great if you could add the same change you did to HOWTO to fio.1, unfortunately they aren't fully synced yet.

**Comment by kylezh** [comment]
@axboe I'm updating the patch. And I will also update the configuration manner that uses a formal iSCSI URL format as `filename`, instead of configuring by three separate options.

**Comment by kylezh** [comment]
@axboe 

I have found some problems with making filename as iSCSI URL.

The problem is, URL contains `/` which is assumed as an OS path separator. fio will try to create a directory when parsing filename that would fail of course.

I was trying to add a new flag to ioengine to indicate that creating a directory is not necessary. However, because ioengine is not loaded when the filename was parsing, so the flag makes no effect. I was able to add a fio option to do that. It works, but I think it would be better to be a ioengine flag, instead of a fio option.

Any suggestion for solving this problem?

**Comment by kylezh** [comment]
Hi @axboe, I think I found a way of passing iscsi url by filename. This is much simpler and can support more features without adding new options. You could find an example file in examples/libiscsi.fio .

**Comment by axboe** [comment]
Not sure I like having that logic in the open path, it should remain in the setup path. What happens if a file is opened multiple times during the run of the job?

**Comment by kylezh** [comment]
How about move create_work_dirs() in seutp_files()?

BTW, I'm not quite sure the usage of TD_F_DIRS_CREATED. Why not call create_work_dirs for each file?

**Comment by axboe** [comment]
You are right, for some reason I totally missed the TD_F_DIRS_CREATED flag. With that in mind, I think the change is fine.

**Comment by axboe** [comment]
Actually, the problem is that it's a per-td thing, not per file. So putting it in generic_open_file() doesn't make a whole lot of sense. setup_files() would definitely be a better spot.

**Comment by kylezh** [comment]
I have moved create_work_dirs() to seutp_files() and rebased to master.

**Comment by axboe** [comment]
Merged, thanks.

**Pull request merged**
