### PR TITLE
server: fix missing le32_to_cpu conversion when opcode is FIO_NET_CMD_TEXT

### PR DESCRIPTION
**Pull request by tuan-hoang1**
Reported-by: Manuel Gotin <manuel.gotin@ibm.com>
Signed-off-by: Tuan Hoang <tmhoang@linux.ibm.com>

### CODE REVIEW

**Comment by tuan-hoang1** [comment]
Hi, I'm not familiar with fio code base. So there might be some places missing, please advise.

**Comment by axboe** [comment]
Fix looks good to me. Not sure if there are other spots where a BE conversion is missing, but some runtime testing on a BE machine might help verify that (which is how I suspect this one was found). Not a lot of BE left in the world these days...

**Comment by tuan-hoang1** [comment]
OK cool, thanks. Just for your visibility about downstream users, we are using https://github.com/red-hat-storage/ocs-ci to do testing on s390x.

**Comment by axboe** [comment]
Do let me know if you spot more oddities on s390.

**Pull request merged**
