### PR TITLE
doc: clarify that I/O errors may go unnoticed without direct=1

### PR DESCRIPTION
**Pull request by Hi-Angel**
Fixes: https://github.com/axboe/fio/issues/1443

### CODE REVIEW

**Comment by Hi-Angel** [comment]
> I think it should also mention that some variant of fsync or fdatasync would also help

Hmm, not sure I got that… fsync() and fdatasync() are libc functions. I don't really see how information about C functions might be useful to a user of the `fio` application.

> and that this issue is specific to writes as reads will always be sync.

Oh, thanks! I actually was wondering if it works for reads or not. In the end I decided to go on the safe side by being more abstract with a "buffered I/O", but yeah, now that you clarified that I will be more explicit. Thank you!

**Comment by axboe** [comment]
fsync and fdatasync are also fio job options.

**Comment by Hi-Angel** [comment]
Oh, I see! Sorry, thanks, will do

**Comment by Hi-Angel** [comment]
Done, please see if you want anything changed

**Comment by axboe** [comment]
I would probably phrase it as:

Note: a write error from the device may go unnoticed by fio when using buffered IO, as the write() (or similar) system call merely dirties the kernel pages, unless :option:`sync` or :option:`direct` is used. Device IO errors occur when the dirty data is actually written out to disk. If fully sync writes aren't desirable, :option:`fsync` or :option:`fdatasync` can be used as well. This is specific to writes, as reads are always synchronous.

with the right kind of option syntax. And double check that the two sections are the same in fio.1 and the HOWTO, they were different in your patch. Thanks!

**Comment by Hi-Angel** [comment]
Thanks, will do

> And double check that the two sections are the same in fio.1 and the HOWTO, they were different in your patch. Thanks!

But they aren't. Here's a screenshot of the diff — nothing except the syntactic specifics of the two formats is different:
Screenshot_20220817_014444

**Comment by Hi-Angel** [comment]
Done!

**Comment by axboe** [comment]
Thanks!

**Comment by Hi-Angel** [comment]
Thank you! The [docs on the site](https://fio.readthedocs.io/en/latest/fio_doc.html) didn't change though, do they have to be updated separately?

**Comment by vincentkfu** [comment]
https://fio.readthedocs.io/en/latest/ is maintained by someone else

**Pull request merged**
