### PR TITLE
compatible with c++

### PR DESCRIPTION
**Pull request by cooljiansir**
compatible with c++

### CODE REVIEW

**Comment by axboe** [comment]
This doesn't look right at all. Did you mean to cast it? Please don't send patches that haven't been tested, let alone compiled.

**Comment by axboe** [comment]
I suspect this should fix it for you:

http://git.kernel.dk/cgit/fio/commit/?id=8f6d1311afd37bf70b5b0bd7ebb0944ed9460d34

Let me know if that's the case or not.

**Comment by cooljiansir** [comment]
yes, just cast it. 
well, this has been compiled and runs okay on my computer.
How should I write here if I want to make my C++ shared lib (io engine) with it,thanks: )

**Comment by axboe** [comment]
I don't see how that could work at all... It'd be a function call at that point.

Can you expand on your last question?

**Comment by cooljiansir** [comment]
I'm testing libfio_ceph_objectstore.so, it is a plugin written in C++. This works okay with g++ (no warning).
it is something like function call in c, which got me some warning when I make fio.

**Comment by axboe** [comment]
OK, so I think we can close this issue. Current -git should work for you, I believe. If not, reopen and let me know.

**Comment by cooljiansir** [comment]
okay,i'll try it latter.
thx

**Pull request closed without merging**
