### PR TITLE
Make fiologparser_hist.py work for python3

### PR DESCRIPTION
**Pull request by brycepg**

### CODE REVIEW

**Comment by brycepg** [comment]
I definitely agree @sitsofe. I decided to make the problem `map` functions list comprehensions since they are much more readable anyway.

**Comment by sitsofe** [comment]
@brycepg Assuming it works with both Python 2 and Python 3 this looks good. Any chance you could add your "Signed-off-by:" (e.g. like https://github.com/axboe/fio/commit/f5ec81235eaf21bd3a97556427d4a84e48a87e54 ) to the commit?

**Comment by sitsofe** [comment]
I can confirm that this commit makes the script python3 compatible while remaining usable on with python2. With the previously mentioned change and possibly a comment saying the script is python3 compatible I think this should be good to go.

**Comment by axboe** [comment]
Pulled, thanks everyone.

**Pull request merged**
