### PR TITLE
Allow build software to inject further C build flags

### PR DESCRIPTION
**Pull request by martin21**
This is useful for dpkg and oder packaging software to inject hardening
options like -fPIE -pie for position independent builds which allow for
address space randomization.

### CODE REVIEW

**Comment by axboe** [comment]
There's already EXTFLAGS for this, can't we reuse that?

**Comment by martin21** [comment]
On Mittwoch, 25. Mai 2016 08:53:12 CEST Jens Axboe wrote:
> There's already EXTFLAGS for this, can't we reuse that?

Well, I just used what works with the standard Debian hardening build 
mechanism using the path of least resistance. I could try to deviate from that 
and set the hardening flags in EXTFLAGS.

But what does speak against just adding to CFLAGS like the makefile does it 
with LDFLAGS already?

Thanks,
-- 
Martin

**Comment by axboe** [comment]
We can do that, but I think we need to do a few cleanups for that too. Currently the configure script outputs CFLAGS, but we override them in the Makefile. If we make the CFLAGS statement in the Makefile additive, then we have duplicate flags. Would be nice to clean up that eyesore too.

**Comment by martin21** [comment]
What do you suggest? Remove duplicate CFLAGS from Makefile?

**Comment by axboe** [comment]
Yes. If we just merge this change, then we'll have -D_GNU_SOURCE -include config-host.h twice, for instance, since it's set in both CFLAGS and BUILD_CFLAGS.

**Pull request closed without merging**
