### PR TITLE
windowsaio: obey sequential/random I/O hinting

### PR DESCRIPTION
**Pull request by sitsofe**
The existing code for selecting whether sequential or random I/O is used seems a bit strange in engines/windowsaio.c. This commit makes it mirror what's done over in td_io_open_file() of ioengines.c. I passed up the chance to stick an `assert(0)` on the default: case to again mirror what is done elsewhere - let me know if this was wrong.

### CODE REVIEW

**Comment by axboe** [comment]
Looks good to me, but I'd really like someone with some Windows knowledge to review it. Can you check with Rebecca Cran if she likes it?

**Comment by sitsofe** [comment]
@bcran What do you think of these changes?

**Comment by bcran** [comment]
Looks good to me too. It makes sense to only tell the kernel what type of workload will be used when the user asks us to, instead of always setting it based on the workload type read/write/randread/etc.

**Comment by axboe** [comment]
Merged, thanks.

**Pull request merged**
