### PR TITLE
Support for alternate epochs in fio log files.

### PR DESCRIPTION
**Pull request by aggieNick02**
This is a first pass at support for issue https://github.com/axboe/fio/issues/1314. Definitely open to feedback on the details.

To start, since `gettimeofday()` is basically equivalent to `clock_gettime()` with a `clock_id` of `CLOCK_REALTIME=0`, I've basically made `log_alternate_epoch` and `log_unix_epoch` equivalent options, with the latter kept for compatibility. Obtaining new epochs is then accomplished by providing `log_alternate_epoch_clock_id` in conjunction with either boolean option `log_alternate_epoch` or `log_unix_epoch`. If the boolean options are false, `log_alternate_epoch_clock_id` has no effect.

I've also updated the windows implementation of `clock_gettime()` to behave for `CLOCK_MONOTONIC_RAW` as it currently does for `CLOCK_MONOTONIC`, since `QueryPerformanceCounter` is not affected by NTP.

### CODE REVIEW

**Comment by aggieNick02** [comment]
Updated PR to fix windows builds

**Comment by ammarfaizi2** [comment]
@aggieNick02 Please use a `Signed-off-by` tag with your real name and email at the end of your commit message. See the commit history for examples.

Also don't make the commit title too long like that (the first line), as it will be used to generate the shortlog (https://brick.kernel.dk/snaps/fio-3.28.shortlog.txt). Maybe take the maximum of 72 chars (or hard limit 80 chars)?

**Comment by aggieNick02** [comment]
Sure, thanks, I'll take care of those. Should I just setup a new PR with the commits with the appropriate `Signed-off-by` tag and commit title? Or fix and then force push to the existing PR?

**Comment by ammarfaizi2** [comment]
Force push in PR is fine.

**Comment by aggieNick02** [comment]
Updated PR with single commit with commit message that has title and signoff. Just let me know if there's anything else or any feedback on the changes. Thanks!

**Pull request merged**
