### PR TITLE
goptions: correct postfix

### PR DESCRIPTION
**Pull request by gloit042**
Signed-off-by: Jiahao Li gloit042@gmail.com

### CODE REVIEW

**Review by sitsofe — CHANGES_REQUESTED** [review]
Some superficial comments. Could you:
 - Prefix the area on your commit titles (see https://github.com/axboe/fio/pull/1050#issuecomment-663606909 )? Maybe `goptions:` or `gfio` based on what I see in https://github.com/axboe/fio/commits/4a1c432eead6db58713bdd3439ecafc0b36956a5/goptions.c ...
- Add your Signed-off-by ?

Wow someone still using gfio! You wouldn't want to port it to a later version of GTK too would you? :-)

**Comment by gloit042** [comment]
Happened to find it when I tried to locate the cause of #1117  😂

**Comment by sitsofe** [comment]
:-) Title still doesn't look right on the commit (the title of the pull request won't matter...)

**Comment by sitsofe** [comment]
Maybe `goptions: correct postfix` for the title but in general looks fine.

@axboe do you want to pull this one?

**Pull request merged**
