### PR TITLE
add pmemblk engine

### PR DESCRIPTION
**Pull request by bgbhpe**
Seeking comments on a new IO engine utilizing the NVML libpmemblk.  More information on libpmemblk and the NVML is available here http://pmem.io/nvml/.

### CODE REVIEW

**Comment by axboe** [comment]
I'll take a look when I'm back from vacation next week. But some initial comments:

1) If this is going into fio git, then you don't need to keep the external engine hooks. Get rid dlym checks, and the defines.
2) Add an example/ job file that uses it.

**Comment by axboe** [comment]
Additionally, enable it by default on the appropriate platforms, and I don't think we need a --disable thing for configure either.

**Comment by axboe** [comment]
I have merged this, but you still had missing bits. You didn't wire up the engine through options.c, I'm assuming you originally used this as an external engine? I've added some documentation bits as well, and cleaned up the coding style.

**Comment by bgbhpe** [comment]
Thanks, Jens.  Sorry for the delayed reply, I'd addressed some of your feedback, but then got caught up with some other stuff.  Yes, it was originally an external engine.

**Comment by axboe** [comment]
No worries! I've done some cleanups around it, when you have time it would be great if you could test it and provide any comments on things that you feel need changing.

**Pull request merged**
