### PR TITLE
Six small patches

### PR DESCRIPTION
**Pull request by bvanassche**
The patches in this series are the result of code inspection or analysis of Coverity complaints.

### CODE REVIEW

**Comment by vincentkfu** [comment]
This PR breaks the Windows build

**Comment by bvanassche** [comment]
Hi Vincent, please provide more information. I tried to build fio in a Cygwin shell before I submitted this pull request but gave up trying to unbreak the Windows build because I discovered many issues with the Windows build that predate this pull request.

**Comment by axboe** [comment]
Oops, I'll revert that particular change for now.

**Comment by axboe** [comment]
@bvanassche The build error (and setup) is shown in the link that Vincent provided.

**Comment by vincentkfu** [comment]
I set up a server to do fio Windows builds and was able to build successfully with the following packages:
- libssp0
- make
- mingw64-x86_64-CUnit, binutils, gcc-core, headers, runtime, zlib

There's actually also a problem building t/read-to-pipe-async under Windows:
```
12:32:24      CC t/read-to-pipe-async.o
12:32:24      CC unittests/unittest.o
12:32:25  t/read-to-pipe-async.c: In function 'reader_work':
12:32:25  t/read-to-pipe-async.c:285:9: warning: implicit declaration of function 'pread'; did you mean 'read'? [-Wimplicit-function-declaration]
12:32:25     ret = pread(work->fd, buf, left, off);
12:32:25           ^~~~~
12:32:25           read
```

**Pull request merged**
