### PR TITLE
use poll() and rbd_poll_io_events to speed up io retrieval.

### PR DESCRIPTION
**Pull request by liupan1111**
Hi,
In Aug. 2015, a new function rbd_poll_io_events is added in Ceph. I use it to speed up io retrieval. I tested by using P3700 SSD and ceph_jewel(bluestore), find the iops and latency has 10% improvement.

### CODE REVIEW

**Comment by liupan1111** [comment]
Hi Axboe,

I also gave a comment in #258, I suggest we add a "check_format.sh" to check and adjust the coding style by using the tool "astyle". If you agree, I could give this help.

**Comment by axboe** [comment]
Pulled this in, with a cleanup commit on top.

**Comment by axboe** [comment]
As for something for checking the format, if you want to work on it, go ahead. I try not to be too picky about format, but I will complain about gross violations like tabs, braces, or style that isn't consistent.

**Comment by liupan1111** [comment]
not picky, I appreciate. Thanks

**Pull request merged**
