### PR TITLE
Rewrote libhdfs engine

### PR DESCRIPTION
**Pull request by fbacchella**

### CODE REVIEW

**Comment by axboe** [comment]
That looks a lot better! Only question is why the changes to options.h?

**Comment by fbacchella** [comment]
Because there is too much options. And you store them in a bit mask or something like than. By activating only used options, it reduced the needed length.

**Comment by axboe** [comment]
I just extended the bitfields to 64-bit instead, see current -git. I think that's cleaner than having to provide ifdefs, and have different numbering depending on what is available. This could break client/server, for instance.

**Comment by fbacchella** [comment]
I agree totally. That's much better this way. I will fix my pull request and resubmit.

**Comment by fbacchella** [comment]
It should be better now. There is a little reformatting because of mixed space and tabulation in options.h. Do you want a separate commit to fix that

**Comment by axboe** [comment]
No that all looks fine, pulled! Thanks.

**Pull request merged**
