### PR TITLE
Add cpu/op and CPU usr/sys ms to json

### PR DESCRIPTION
**Pull request by useche**
Add cpu/op and CPU usr/sys ms to json

Having these times might be useful to calculate any events waited by the CPU time (e.g. CPU/op).

Signed-off-by: Luis Useche <useche@gmail.com>

### CODE REVIEW

**Comment by ammarfaizi2** [comment]
The second commit is missing a `Signed-off-by` tag.

**Comment by useche** [comment]
> 

Done

**Comment by vincentkfu** [comment]
It seems like (CPU ms) / op can actually be calculated based on the values already reported in the normal output. So having fio do this calculation and reporting the result is merely for convenience. Can you provide a more detailed justification explaining why it is useful to report this value?

The label in the normal output is "cpu msec/op" but the actual calculation is:

`cpu_per_op = (double) ts->total_complete / (usr_cpu + sys_cpu);`

These two are inconsistent and the denominator is the sum of two percentages.

If you are adding a field to the normal output please add the same field to the JSON output. I think it's fine for the JSON output to have more information than the normal output but it shouldn't have less.

With changes in the output fio.1 and HOWTO should be updated as well.

**Comment by useche** [comment]
Hi Vincent. Thanks for taking a look. 

> It seems like (CPU ms) / op can actually be calculated based on the values already reported in the normal output. So having fio do this calculation and reporting the result is merely for convenience. Can you provide a more detailed justification explaining why it is useful to report this value?

Although the total number of I/Os is available, the CPU time in milliseconds is not. The CPU in milliseconds is necessary to correctly make this calculation.

> The label in the normal output is "cpu msec/op" but the actual calculation is:
> 
> `cpu_per_op = (double) ts->total_complete / (usr_cpu + sys_cpu);`
> 
> These two are inconsistent and the denominator is the sum of two percentages.

You are right. I'm not sure what happened. The code that makes sense is up now.

> If you are adding a field to the normal output please add the same field to the JSON output. I think it's fine for the JSON output to have more information than the normal output but it shouldn't have less.

Done.

> With changes in the output fio.1 and HOWTO should be updated as well.

Done

**Comment by vincentkfu** [comment]
> Hi Vincent. Thanks for taking a look.
> 
> > It seems like (CPU ms) / op can actually be calculated based on the values already reported in the normal output. So having fio do this calculation and reporting the result is merely for convenience. Can you provide a more detailed justification explaining why it is useful to report this value?
> 
> Although the total number of I/Os is available, the CPU time in milliseconds is not. The CPU in milliseconds is necessary to correctly make this calculation.
> 

CPU milliseconds can be obtained by multiplying runtime by the sum of the user and system CPU usage percentages.

**Comment by useche** [comment]
> > Hi Vincent. Thanks for taking a look.
> > > It seems like (CPU ms) / op can actually be calculated based on the values already reported in the normal output. So having fio do this calculation and reporting the result is merely for convenience. Can you provide a more detailed justification explaining why it is useful to report this value?
> > 
> > 
> > Although the total number of I/Os is available, the CPU time in milliseconds is not. The CPU in milliseconds is necessary to correctly make this calculation.
> 
> CPU milliseconds can be obtained by multiplying runtime by the sum of the user and system CPU usage percentages.

You are right, we can obtain the CPU time using this calculation. Then, it will be just for convenience for one time runs. I was more interested in the json one for automation, but we can get the CPU milliseconds with this calculation too. With that, it sounds like these patches are not that useful. If you think that too, we may abandon these patches.

**Comment by vincentkfu** [comment]
I don't have any specific objection to adding this value but if you can obtain what you need with no code changes, then I see no compelling need for these patches. Moreover, it seems like fio's output is already complicated enough that it was difficult for a motivated person to find the runtime. In that case we should be wary of making it even more complicated.

**Pull request closed without merging**
