### PR TITLE
use 'const' and 'static' where it is required

### PR DESCRIPTION
**Pull request by dpronin**
protect variables from programmer's point of view and hide several by  'static' variables

Signed-off-by: Denis Pronin <dannftk@yandex.ru>

### CODE REVIEW

**Comment by dpronin** [comment]
@axboe are there any ideas why `constness` and/or `static` of some variables/constants and/or parameters may affect runtime tests? I don't have one

**Comment by vincentkfu** [comment]
I don't know why but your changes make the test jobs segfault on windows.

**Comment by dpronin** [comment]
I presume, because I used to be a developer under windows, `static const` variables Windows compiler places in read-only segment section in binary that is mapped within PAGE with READ ONLY protection, and probably, there is some code that attempts to write to this section/mapped page

**Comment by vincentkfu** [comment]
Actually the Windows failures started with the double free fix. So this patch is not the cause.

**Comment by dpronin** [comment]
> Actually the Windows failures started with the double free fix. So this patch is not the cause.

Is there any opportunity to check these tests without launching up Windows as a virtual machine? Is there an emulator of cygwin under Linux?

**Comment by vincentkfu** [comment]
None that I know of.

**Comment by dpronin** [comment]
It's a pity

**Pull request closed without merging**
